name: Build Vite For Github Pages
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CI - Checkout
        uses: actions/checkout@v3

      - name: CI - Node
        uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: CI - Generate Static Files
        run: |
          npm ci
          npm run build

      - name: CI - Init dist repo and commit
        run: |
          cd dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'automatic build'

      - name: CI - Folder Lookup
        run: ls -a

      - name: CD - Push to deployment branch
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist
